spring:
  application:
    name: CinemaFlix
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/cinema_database
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    hibernate:
      ddl-auto: update
  mail:
    username: mmmdliayxan2107@gmail.com
    host: smtp.gmail.com
    port: 587
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master-yml-test.yaml
    enabled: true
secretKey: VG8gZW5jb2RlIGJpbmFyaWVzIChsaWtlIGltYWdlcywgZG9jdW1lbnRzLCBldGMuKSB1c2UgdGhlIGZpbGUgdXBsb2FkIGZvcm0gYSBsaXR0bGUgZnVydGhlciBkb3duIG9uIHRoaXMgcGFnZS4K